ALL_CITIES = [
    "Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan",
    "Nizhny Novgorod", "Chelyabinsk", "Samara", "Omsk", "Rostov-on-Don",
    "Ufa", "Krasnoyarsk", "Voronezh", "Perm", "Volgograd",
    "Krasnodar", "Saratov", "Tyumen", "Tolyatti", "Izhevsk",
    "Barnaul", "Irkutsk", "Khabarovsk", "Vladivostok", "Yaroslavl",
    "Makhachkala", "Tomsk", "Orenburg", "Kemerovo", "Novokuznetsk",
    "Ryazan", "Astrakhan", "Penza", "Lipetsk", "Tula",
    "Kaliningrad", "Kursk", "Sochi", "Murmansk", "Arkhangelsk",
    "Yakutsk", "Norilsk", "Anadyr", "Magadan", "Petropavlovsk-Kamchatsky",
    "London", "Paris", "Berlin", "Madrid", "Rome",
    "Amsterdam", "Vienna", "Prague", "Warsaw", "Budapest",
    "Brussels", "Copenhagen", "Stockholm", "Oslo", "Helsinki",
    "Dublin", "Lisbon", "Athens", "Zurich", "Geneva",
    "Munich", "Hamburg", "Milan", "Barcelona", "Naples",
    "Reykjavik", "Kyiv", "Minsk", "Bucharest", "Sofia",
    "Belgrade", "Zagreb", "Bratislava", "Ljubljana", "Tallinn",
    "Riga", "Vilnius", "Istanbul", "Ankara", "Tbilisi",
    "Yerevan", "Baku", "Nur-Sultan", "Almaty", "Tashkent",
    "Bishkek", "Dushanbe", "Ashgabat", "New York", "Los Angeles",
    "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio",
    "San Diego", "Dallas", "San Francisco", "Seattle", "Denver",
    "Boston", "Miami", "Toronto", "Montreal", "Vancouver",
    "Mexico City", "Guadalajara", "Havana", "Bogota", "Lima",
    "Santiago", "Buenos Aires", "Sao Paulo", "Rio de Janeiro", "Brasilia",
    "Caracas", "Quito", "La Paz", "Montevideo", "Asuncion",
    "Cairo", "Lagos", "Kinshasa", "Nairobi", "Casablanca",
    "Addis Ababa", "Cape Town", "Johannesburg", "Accra", "Dakar",
    "Algiers", "Tunis", "Khartoum", "Dar es Salaam", "Luanda",
    "Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Hong Kong",
    "Tokyo", "Osaka", "Nagoya", "Seoul", "Busan",
    "Bangkok", "Jakarta", "Manila", "Singapore", "Kuala Lumpur",
    "Ho Chi Minh City", "Hanoi", "Taipei", "Delhi", "Mumbai",
    "Bangalore", "Kolkata", "Chennai", "Hyderabad", "Karachi",
    "Lahore", "Dhaka", "Kathmandu", "Colombo", "Tehran",
    "Baghdad", "Riyadh", "Jeddah", "Dubai", "Abu Dhabi",
    "Doha", "Kuwait City", "Amman", "Beirut", "Jerusalem",
    "Sydney", "Melbourne", "Brisbane", "Perth", "Auckland",
    "Wellington",
]
